accounts/urls.py

from django.urls import include, path
from . import views
app_name='accounts'
urlpatterns = [
    path('', views.testfun, name='index'),
    path('register/',views.reg,name='reg'),
    path('login/',views.log,name='log'),
    path('logout/',views.lout,name='lout'),
    path('buy/<slug:slug>/',views.dgame,name='dgame'),
    path('profile/',views.puser,name='profile')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from games.models import Game

# Create your models here.
class profile(models.Model):
    user=models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    pgames=models.ManyToManyField(Game,blank=True)
    
    def __str__(self):
        return self.user.username
        
class download(models.Model):
    game=models.ForeignKey(Game,on_delete=models.SET_NULL,null=True)
    owner=models.ForeignKey(profile,on_delete=models.SET_NULL,null=True)
    credit_card_no=models.CharField(max_length=10)
    pin=models.IntegerField()
    date=models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from . import models

class payment_portal(forms.ModelForm):
    class Meta:
        model=models.download
        fields=['pin','credit_card_no']

accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from . import forms
from .models import Game
from .models import profile
# Create your views here.
def testfun(request):
 return render(request,'accounts/test.html')
def reg(request):
 if request.method=='POST':  
  form=UserCreationForm(request.POST)
  if form.is_valid():
     user=form.save()
     login(request,user)
     return redirect('games:list')
 else:    
  form=UserCreationForm()    
 return render(request,'accounts/accountreg.html',{'form':form}) 
def log(request):
  if request.method=='POST':
   form=AuthenticationForm(data=request.POST)
   if form.is_valid():
     user=form.get_user()
     login(request,user)
     return redirect('games:list')
  else:
    form=AuthenticationForm()
  return render(request,'accounts/login.html',{'form':form})
  
def lout(request):
    if(request.method=='POST'):
        logout(request)
        return redirect('home')
        
def dgame(request,slug):
    game=Game.objects.get(slug=slug)
    if request.method=='POST':
        form=forms.payment_portal(request.POST)
        if(form.is_valid()):
            inst=form.save(commit=False)
            p1=profile.objects.get(user=request.user)
            inst.owner=p1
            inst.game=game
            inst.save()
            
            p1.pgames.add(game)
            p1.save()
            return redirect('games:list')
    else:
        form=forms.payment_portal()
    return render(request,'accounts/downloadg.html',{'form':form,'game':game})
    
    
    
def puser(request):
    p=profile.objects.get(user=request.user)
    return render(request,'accounts/dispprofile.html',{'p':p})

accounts/templates/accounts/accountreg.html
<html>
<body>
<form class="site-form" action="{% url 'accounts:reg' %}" method="post">
{% csrf_token %}
{{form}}
<input type="submit" value="register">
</form>
</body>
</html>

accounts/templates/accounts/dispprofile.html
{% load static %}
<html>
<head>
<link rel="stylesheet" href="{% static 'gl.css' %}">
</head>
<body>
<div class="main">
<div class="left">
<h1>{{ user.username }}</h2>
 {% for pro in p.pgames.all %}
	<div style="border-color:black;border-style:solid;" >
	 <p>{{ pro.game_name }}</p>
	 <p>{{ pro.game_publisher }}</p>
	 <p>{{ pro.price }}</p>
	</div>
 {% endfor %}
</div>
<div class="right">
<div style="margin:30px">
<form action="{% url 'accounts:lout' %}" method="post" >
{% csrf_token %}
<button type="submit">logout</button>

</form>
<br>
<br>
<br>
<a href="{% url 'freegame' %}" style="text-decoration:none">FREE GAMES</a>
<br><br><br><br>
<a href="{% url 'games:list' %}" style="text-decoration:none">GAME LIST</a>
</div>
</div>
</div>
</body>
</html>

accounts/templates/accounts/downloadg.html
<html>
<body>
<p>price:{{ game.price }}</p>
<p> name:{{ game.game_name }}</p>
<form action="{% url 'accounts:dgame' slug=game.slug %}" method="post">
{% csrf_token %}
{{ form }}<br>
<input type="submit" value="download">
</form>
</body>
</html>

accounts/templates/accounts/login.html
<html>
<body>
<form class="login-form" action="{% url 'accounts:log' %}" method="post">
{% csrf_token %}
{{form}}
<input type="submit" value="login">
</form>
</body>
</html>

accounts/templates/accounts/test.html
<html>
<body>
<h1>
hello
</h1>
</body>
</html>