games/urls.py
from django.urls import include, path
from . import views
app_name='games'
urlpatterns = [
    path('', views.listfun, name='list'),
    path('<slug:slug>/',views.game_detail,name='detail')
]

games/models.py
from django.db import models
# Create your models here.
class Game(models.Model):
    game_name=models.CharField(max_length=30)
    game_publisher=models.CharField(max_length=30)
    game_description=models.TextField()
    slug=models.SlugField()
    price=models.IntegerField()
    date=models.DateTimeField(auto_now_add=True)
    thumb=models.ImageField(blank=True)
    
    def __str__(self):
        return self.game_name
        
        
        
        

    

games/views.py

from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Game
# Create your views here.
def listfun(request):
    games=Game.objects.all()
    return render(request,'games/gamel.html',{'games':games})
    
def game_detail(request,slug):
    game=Game.objects.get(slug=slug)
    return render(request,'games/gamed.html',{'game':game})
    

games/templates/games/gamed.html
{% load static %}
<html>
<head>
<link rel="stylesheet" href="{% static 'gl.css' %}">
</head>
<body>
<div class="main">
<div class="left">
 <div>
 <h2 color="#d2a679">{{ game.game_name }}</h2>
 <p>publisher:{{ game.game_publisher }}</p>
 <p>description:{{ game.game_description }}</p>
 <p>price:{{ game.price }}</p>
 </div>
 <img src="{{ game.thumb.url }}" margin-top="10px" width="500px" height="500px">
 {% if game in user.profile.pgames.all %}
<h2> ALREADY OWNED</h2>
{% else %}
<a href="{% url 'accounts:dgame' slug=game.slug %}"> DOWNLOAD </a>
{% endif %}
</div>

<div class="right">
<div style="margin:30px">
<form action="{% url 'accounts:lout' %}" method="post" >
{% csrf_token %}
<button type="submit">logout</button>

</form>
</div>
</div>
</div>
</body>
</html>

games/templates/games/gamel.html
{% load static %}
<html>
<head>
<link rel="stylesheet" href="{% static 'gl.css' %}">
</head>
<body>
<div class="main">
<div class="left">
 {% for game in games %}
	<div style="border-color:black;border-style:solid;" >
	 <a href="{% url 'games:detail' slug=game.slug %}">{{ game.game_name }}</a>
	 <p>{{ game.game_publisher }}</p>
	 <p>{{ game.price }}</p>
	</div>
 {% endfor %}
</div>
<div class="right">
<div style="margin:30px">
<form action="{% url 'accounts:lout' %}" method="post" >
{% csrf_token %}
<button type="submit">logout</button>

</form>
<br>
<br>
<br>
<a href="{% url 'freegame' %}" style="text-decoration:none">FREE GAMES</a>
<br><br><br>
<a href="{% url 'accounts:profile' %}" style="text-decoration:none">PROFILE</a>
</div>
</div>
</div>
</body>
</html>